name: customer_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.9.3
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  firebase_storage: ^11.2.8
  flutter_local_notifications: ^16.1.0
  get: ^4.6.6
  image_picker: ^1.0.4
  intl: ^0.18.1
  syncfusion_flutter_datepicker: ^23.1.40
  pin_code_fields: ^8.0.1
  country_code_picker: ^3.0.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  flutter_share: ^2.0.0
  clipboard: ^0.1.3
  geolocator:
  lottie: ^2.6.0
  geocoding: ^2.1.1
  flutter_svg: ^2.0.7
  geoflutterfire2: ^2.3.15
  place_picker: ^0.10.0
  google_sign_in: ^6.2.1
  uuid: ^4.1.0
  dotted_border: ^2.1.0
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  url_launcher: ^6.1.14
  flutter_rating_bar: ^4.0.1
  flutter_easyloading: ^3.0.5

  #payment_dependencies
  flutter_stripe: ^9.4.0
  flutter_paypal_native: ^2.0.1


  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Figtree-Regular
      fonts:
        - asset: assets/fonts/Figtree-Regular.ttf

    - family: Figtree-Medium
      fonts:
        - asset: assets/fonts/Figtree-Medium.ttf

    - family: Figtree-Bold
      fonts:
        - asset: assets/fonts/Figtree-Bold.ttf

    - family: Figtree-SemiBold
      fonts:
        - asset: assets/fonts/Figtree-SemiBold.ttf

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/gif/

